# File generated by cdo from README.md; DO NOT EDIT.

SHELL=bash
.SHELLFLAGS=-e -o pipefail -c

.PHONY: __help__
__help__:
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Targets:'
	@echo '  all      Run all'
	@echo '  doc      Update documentation'
	@echo '  it       Run the integration tests'
	@echo '  lint     Run the linter'
	@echo '  makefile Generate the Makefile'
	@echo '  security Run security and vulnerability checks'
	@echo '  test     Test the test extensions'

# Run all
.PHONY: all
all: lint security test it doc makefile

# Update documentation
.PHONY: doc
doc: 
	@(\
		mdcode update;\
	)

# Run the integration tests
.PHONY: it
it: 
	@(\
		bats test;\
	)

# Run the linter
.PHONY: lint
lint: 
	@(\
		K6_CI_REF=$$(grep -oE 'grafana/k6-ci/[^@[:space:]]+@[A-Za-z0-9._/-]+' .github/workflows/k6-ci.yml | head -n1 | cut -d@ -f2);\
		curl -fsSL "https://raw.githubusercontent.com/grafana/k6-ci/$${K6_CI_REF}/.golangci.yml" -o .golangci.yml;\
		go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$$(head -n1 .golangci.yml | tr -d '# ') run --config=.golangci.yml ./...;\
	)

# Generate the Makefile
.PHONY: makefile
makefile: 
	@(\
		cdo --makefile Makefile;\
	)

# Run security and vulnerability checks
.PHONY: security
security: 
	@(\
		gosec -quiet ./...;\
		govulncheck ./...;\
	)

# Test the test extensions
.PHONY: test
test: 
	@(\
		bats -r ext;\
	)
