# File generated by cdo from README.md; DO NOT EDIT.

SHELL=bash
.SHELLFLAGS=-e -o pipefail -c

.PHONY: __help__
__help__:
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Targets:'
	@echo '  all      Run all'
	@echo '  doc      Update documentation'
	@echo '  it       Run the integration tests'
	@echo '  it-build Run the integration tests of the build command'
	@echo '  it-run   Run the integration tests of the run command'
	@echo '  lint     Run the linter'
	@echo '  makefile Generate the Makefile'
	@echo '  test     Test the test extensions'

# Run all
.PHONY: all
all: lint test it doc makefile

# Update documentation
.PHONY: doc
doc: 
	@(\
		mdcode update;\
	)

# Run the integration tests
.PHONY: it
it: 
	@(\
		bats -r test;\
	)

# Run the integration tests of the build command
.PHONY: it-build
it-build: 
	@(\
		bats test/build.bats;\
	)

# Run the integration tests of the run command
.PHONY: it-run
it-run: 
	@(\
		bats test/run.bats;\
	)

# Run the linter
.PHONY: lint
lint: 
	@(\
		golangci-lint run ./...;\
	)

# Generate the Makefile
.PHONY: makefile
makefile: 
	@(\
		cdo --makefile Makefile;\
	)

# Test the test extensions
.PHONY: test
test: 
	@(\
		bats -r ext;\
	)

